//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBookApp1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration.Conventions;

    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int PersonId { get; set; }
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        [DisplayName("Middle Name")]
        public string MiddleName { get; set; }
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        [DisplayName("Date of Birth")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        [DisplayName("Added On")]
        public System.DateTime AddedOn { get; set; }
        [DisplayName("Added By")]
        public string AddedBy { get; set; }
        [DisplayName("Home Address")]
        public string HomeAddress { get; set; }
        [DisplayName("City")]
        public string HomeCity { get; set; }
        [DisplayName("Facebook Id")]
        public string FaceBookAccountId { get; set; }
        [DisplayName("LinkedIn Id")]
        public string LinkedInId { get; set; }
        [DisplayName("Update On")]
        public Nullable<System.DateTime> UpdateOn { get; set; }
        [DisplayName("Image Path")]
        public string ImagePath { get; set; }
        [DisplayName("Twitter Id")]
        public string TwitterId { get; set; }
        [DisplayName("Email Id")]
        public string EmailId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
        protected void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            modelBuilder.Entity<Person>()
                .HasMany(c => c.Contacts)
                .WithRequired().HasForeignKey(c => c.PersonId)
                .WillCascadeOnDelete();
        }
    }
}
